# Generated by Django 3.1.1 on 2020-09-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comments_body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='comments_name',
        ),
    ]
