# Generated by Django 3.1.1 on 2020-09-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200913_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_name',
            new_name='name',
        ),
    ]
