# Generated by Django 3.1.1 on 2020-09-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200913_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body_text',
            new_name='body',
        ),
    ]
